### ISSUE TITLE
Bump minimum GCC version

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods_development_environment#116]
We need to bump the minimum GCC version we use to at least 11, as clang's compatibility with coroutines in libstdc++ was not ironed out until libstdc++ 11: llvm/llvm-project#47516

We might have to pick GCC 12 on Ubuntu/Debian, as I seem to remember they use the previous version of libstdc++ relative to the GCC being used. I could be misremembering though.

**Comment by trel** [comment]
clang's compatibility?   oh i think this is just a copy/pasta-o.

**Comment by SwooshyCueb** [comment]
Nope, that's intentional. The build of gcc we build clang with determines the version of libstdc++ clang uses.

**Comment by SwooshyCueb** [comment]
Given that we will be changing the relevant project to no longer use coroutines, I don't think we need to do this any more
