### ISSUE TITLE
in a centos:7 docker, irods 4.3.0 silently fails to configure rsyslog

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods_development_environment#12]
steps to reproduce:
   - checkout from this [branch](https://github.com/d-w-moore/irods_development_environment/tree/centos7_var_log_irods)
   - per the README, run: `./run_debugger.sh  -V volumes.include.sh  -d .. -p centos7 --ninja `
   - do the docker exec -it `<container_id> bash` to get into the container
   - there, run a script to clear out 4.2.x packages and build/install master branch of irods:
     ```
     bash -e  /tmp/c7.history_no_var_log_irods
     ```
the result will be an apparently correct iRODS install, but with no `/var/log/irods/irods.log` directory and file created.
(Note that rsyslogd is launched from the above mentioned bash script. Also, a patch was needed to  get rsyslog working in the container.  None of this is true , nor does the issue itself occur, in a non-containerized Centos 7 install ).

**Comment by alanking** [comment]
This has also been observed in `irods_testing_environment`. `debian:11` also fails to configure `rsyslog`, but not so silently. I think we just need to enable systemd in the container, somehow:

see: https://stackoverflow.com/questions/54079586/make-systemctl-work-from-inside-a-container-in-a-debian-stretch-image
see: https://developers.redhat.com/blog/2016/09/13/running-systemd-in-a-non-privileged-container

**Comment by SwooshyCueb** [comment]
Given that iRODS no longer configures rsyslog, and that we now preconfigure rsyslog during the image build process, I think we can close this issue now. Thoughts?

**Comment by alanking** [comment]
I agree. If https://github.com/irods/irods_development_environment/issues/78 solved this issue, then I think that this can be closed.
