### ISSUE TITLE
Enhancement Thought: hadolint

### ISSUE THREAD

**Issue by kript** [irods/irods_development_environment#28]
Hi folks,

A couple of UGM's ago, @alanking asked for recommendations on best practices for Docker Containers. This isn't that, but it might help... :wink: 

We've recently started using [hadolint](https://github.com/hadolint/hadolint), and it seems to be providing helpful feedback on many of the Docker images I use, so I thought I'd pass it on. 

Something I find very useful is the ability to run it via docker.

I'd be happy to collaborate on an MR with the changes if that's of interest?

```
$ sudo docker run --rm -i hadolint/hadolint < ./Dockerfile.irods_core_builder.ubuntu18
-:8 DL3008 warning: Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
-:8 DL3015 info: Avoid additional packages by specifying `--no-install-recommends`
-:30 DL4006 warning: Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using /bin/sh in an alpine image or if your shell is symlinked to busybox then consider explicitly setting your SHELL to /bin/ash, or disable this check
-:35 DL3008 warning: Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
-:35 DL3015 info: Avoid additional packages by specifying `--no-install-recommends`
-:49 DL3008 warning: Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
-:49 DL3015 info: Avoid additional packages by specifying `--no-install-recommends`
-:81 DL3020 error: Use COPY instead of ADD for files and folders
```

**Comment by trel** [comment]
I was going to be very very pleased if it was named Hao-lint.

**Comment by kript** [comment]
well, you _could_ fork the project... :innocent:

**Comment by alanking** [comment]
Maybe we can incorporate this into Github actions as a check. Certainly any help on resolving detecting issues are welcome :) Thanks!

**Comment by alanking** [comment]
@trel, did we add this to our Github actions? It seems to be actively critiquing my PRs now... :)

**Comment by alanking** [comment]
Well, @kript, I think we did it?

**Comment by kript** [comment]
Sounds like it!
