### ISSUE TITLE
Add support for 4.3.0-targeted platforms

### ISSUE THREAD

**Issue by alanking** [irods/irods_development_environment#33]
- [x] ubuntu:18.04
- [x] ubuntu:20.04
- [x] debian:11
- [x] centos:7
- [x] almalinux:8

**Comment by alanking** [comment]
@trel / @korydraughn let me know if there are others that need to be added or if the versions are wrong

**Comment by trel** [comment]
looks correct - alma and rocky should be 'identical'...  so we'll probably need to pick one as the canonical version we declare/publish.   RENCI has picked almalinux I think for the VMs downstairs.

**Comment by korydraughn** [comment]
is there a reason against supporting both alma and rocky?

**Comment by trel** [comment]
no, not at all - what i'm saying is that by supporting one, we... I think... will be supporting both.   aka the exact same package will work on both.   but maybe that won't turn out to be true...

**Comment by alanking** [comment]
I'll just add almalinux to start and we'll run it through testing on rockylinux to see if everything works

**Comment by alanking** [comment]
Awaiting rockylinux:8 support in testing environment before closing. See irods/irods_testing_environment#49 for tracking progress on that.

**Comment by alanking** [comment]
rockylinux:8 will no longer be explicitly added to the development or testing environments as almalinux:8 will act as the representative for the el8 platform(s).

Plugin builders should be added for these platforms, but I view this as a separate issue/bigger lift because the underlying machinery in other repositories does not yet support the new platforms.

Removed the last checkbox and closing.
