### ISSUE TITLE
Dockerfiles: empty continuation lines in RUN instructions deprecated

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods_development_environment#40]
Empty continuation lines will become errors in a future release of Docker.
My understanding is that starting a RUN instruction like `RUN \` counts as an empty continuation line.

**Comment by trel** [comment]
is that true?   i see some discussions about false positives of comments within multi-line run commands...

what would be the reasoning for this?

**Comment by SwooshyCueb** [comment]
My understanding is that `RUN \` counts as an empty continuation line.
I did hear about false positives with comments splitting up continuation lines, but we don't do that anywhere AFAIK.

I'll dig into this more.

**Comment by trel** [comment]
definitely willing to follow best practice, but usually best practices make sense.    this one doesn't yet.

**Comment by korydraughn** [comment]
Is this issue resolved?

**Comment by SwooshyCueb** [comment]
Yeah, this one's done.
