### ISSUE TITLE
Avoid use of apt in scripts

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods_development_environment#42]
`apt-get` should be used in lieu of `apt` in scripts when possible. From the `apt` manpage (emphasis mine):
> The [apt](http://manpages.ubuntu.com/manpages/jammy/en/man8/apt.8.html)(8) commandline is designed as an end-user tool and it may change behavior between
> versions. While it tries not to break backward compatibility this is not guaranteed either
> if a change seems beneficial for interactive use.
>
> All features of [apt](http://manpages.ubuntu.com/manpages/jammy/en/man8/apt.8.html)(8) are available in dedicated APT tools like [apt-get](http://manpages.ubuntu.com/manpages/jammy/en/man8/apt-get.8.html)(8) and [apt-](http://manpages.ubuntu.com/manpages/jammy/en/man8/aptcache.8.html)
> [cache](http://manpages.ubuntu.com/manpages/jammy/en/man8/aptcache.8.html)(8) as well.  [apt](http://manpages.ubuntu.com/manpages/jammy/en/man8/apt.8.html)(8) just changes the default value of some options (see [apt.conf](http://manpages.ubuntu.com/manpages/jammy/en/man5/apt.conf.5.html)(5)
> and specifically the Binary scope). So you should prefer using these commands (potentially
> with some additional options enabled) in your scripts as they keep backward compatibility
> as much as possible.

**Comment by korydraughn** [comment]
Anything else left to do for this issue?

**Comment by SwooshyCueb** [comment]
Nope, this one's done
