### ISSUE TITLE
Centos-7 plugin build procedure fails copying the RPM to destination

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods_development_environment#48]
The following Bash script
```
#!/bin/bash
OS=centos-7
#PLUGIN=irods_capability_indexing
PLUGIN=irods_rule_engine_plugin_python
DIR=$(realpath $(dirname $0)/..)
docker run \
           -v "$DIR"/plugin_build_output_dir:/irods_plugin_build \
           -v "$DIR"/"$PLUGIN":/irods_plugin_source \
           -v "$DIR"/plugin_packages_output_dir:/irods_plugin_packages \
           -v "$DIR"/irods_package_output:/irods_packages \
           irods-plugin-builder:${OS} \
           --build_directory /irods_plugin_build
```
(when run from the development environment repo top level directory) experiences an error after the package is built:

```

   ... <CMake completes building .so's, etc, for inclusion in the RPM file> ...

Consolidate compiler generated dependencies of target irods_rule_engine_plugin-python
[100%] Built target irods_rule_engine_plugin-python
Run CPack packaging tool...
CPack: Create package using RPM
CPack: Install projects
CPack: - Run preinstall target for: irods_rule_engine_plugin-python
CPack: - Install project: irods_rule_engine_plugin-python []
CPack: Create package
CPack: - package: /irods_plugin_build/irods-rule-engine-plugin-python-4.3.0.0-1.x86_64.rpm generated.

CPackRPM: Will use GENERATED spec file: /irods_plugin_build/_CPack_Packages/Linux/RPM/SPECS/irods-rule-engine-plugin-python.spec

+ cp -r '/irods_plugin_build/*.' /irods_plugin_packages/
cp: cannot stat '/irods_plugin_build/*.': No such file or directory

```

**Comment by d-w-moore** [comment]
@alanking - I believe you may have given me a fix for this at some point a week or 2 ago.  You pointed me at your dev environment repo, and after pulling and then rebuilding the docker image this was working.

I don't remember what dev branch that was, but if we find it, we should probably turn it into a pull request.

**Comment by trel** [comment]
I see a period at the end of `/irods_plugin_build/*.`

Is that correct?

**Comment by d-w-moore** [comment]
Yes. The extension is being left out in the bash cp command. It actually is an environment set somewhere in the image. If I recall correctly.

**Comment by trel** [comment]
Ah yes.

https://github.com/irods/irods_development_environment/blob/5b58ddb0f8f23a75e4bfd000ba61c9924eed4a52/build_and_copy_plugin_packages_to_dir.sh#L9

**Comment by trel** [comment]
Needs more bumpers... ala...

https://github.com/irods/irods_development_environment/blob/5b58ddb0f8f23a75e4bfd000ba61c9924eed4a52/build_and_copy_packages_to_dir.sh#L27-L30

**Comment by alanking** [comment]
I believe this would be fixed by this PR: https://github.com/irods/irods_development_environment/pull/46

**Comment by alanking** [comment]
I think #44 fixed this. Please confirm.

**Comment by d-w-moore** [comment]
Testing this now.

**Comment by d-w-moore** [comment]
OK I think we're good to close this issue.
