### ISSUE TITLE
building plugins can require PowerTools on almalinux

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods_development_environment#61]

**Comment by SwooshyCueb** [comment]
Quick note: for Rocky Linux 9, the repository has been renamed to crb
https://wiki.rockylinux.org/rocky/repo/#base-repositories

**Comment by d-w-moore** [comment]
Related / same : https://github.com/irods/irods_netcdf/issues/25

**Comment by d-w-moore** [comment]
> Related / same : [irods/irods_netcdf#25](https://github.com/irods/irods_netcdf/issues/25)

This was the error generated from running the plugin builder for irods_netcdf on almalinux8 (with our docker-enabled testing environment), if PowerTools is **_not enabled_**:
```
alma_powertools_for_build, -> main
building irods-netcdf on almalinux8 gives:
============================================
Error: 
 Problem: conflicting requests
  - nothing provides libsz.so.2()(64bit) needed by netcdf-devel-4.7.0-3.el8.x86_64

```

**Comment by d-w-moore** [comment]
And ... verified that this does fix the build process for `irods_netcdf`, and the tests  incidentally were run again, and passed, for `4.3.0.0 `of that plugin.

**Comment by alanking** [comment]
@d-w-moore - Looks like this is done. Please close if true. Thanks!
