### ISSUE TITLE
Document how to deploy a federated architecture

### ISSUE THREAD

**Issue by kript** [irods/irods_development_environment#66]
I had the impression from the talk at the UGM there were some scripts to deploy a federated set of zones which could be used for testing e.g. upgrades, but I don't see them in this repository, have I missed them?

Also a section on how to spin them up would be helpful - there is an example of how to run a single docker container, but not the wider infrastructure.

**Comment by korydraughn** [comment]
Standing up a federated zone, etc. is a feature of the [irods_testing_environment](https://github.com/irods/irods_testing_environment).

This repo is for building the server, icommands, and plugin packages.

**Comment by kript** [comment]
Ooh, that makes sense. The README should probably point to that!

**Comment by kript** [comment]
My suggested wording; https://github.com/irods/irods_development_environment/pull/68
